version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=14701470
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"                     # Порт для API
      - "9001:9001"                     # Порт для панели управления MinIO
    command: server /data --console-address ":9001"

volumes:
  minio_data: