version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"                     # Порт для API
      - "9001:9001"                     # Порт для панели управления MinIO
    command: server /data --console-address ":9001"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"                     # Пробрасываем порт MySQL
    volumes:
      - mysql_data:/var/lib/mysql       # Храним данные вне контейнера
volumes:
  minio_data:
  mysql_data:
